gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#e9ae55"
      - bold
    inactiveBorderColor:
      - "#526970"
    optionsTextColor:
      - "#e9ae55"
    selectedLineBgColor:
      - "#1b2b30"
    cherryPickedCommitBgColor:
      - "#30494c"
    cherryPickedCommitFgColor:
      - "#78c7c4"
    unstagedChangesColor:
      - "#f07167"
    defaultFgColor:
      - "#ddd3b8"
  authorColors:
    "*": "#78c7c4"
  showFileTree: true
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
